-- Create tasks table
CREATE TABLE public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    assigned_to BIGINT REFERENCES public.users(id),
    created_by BIGINT REFERENCES public.users(id),
    due_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create index for tasks
CREATE INDEX idx_tasks_status ON public.tasks(status);
CREATE INDEX idx_tasks_assigned_to ON public.tasks(assigned_to);

-- Enable RLS for tasks
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Create policies for tasks
CREATE POLICY "Users can view assigned tasks"
    ON public.tasks FOR SELECT
    USING (assigned_to = (SELECT id FROM public.users WHERE auth_id = auth.uid()) OR 
           created_by = (SELECT id FROM public.users WHERE auth_id = auth.uid()));

-- Add trigger for updated_at
CREATE TRIGGER update_tasks_updated_at
    BEFORE UPDATE ON public.tasks
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Grant permissions
GRANT ALL ON public.tasks TO authenticated;

-- Clear existing data
TRUNCATE public.user_stats CASCADE;
TRUNCATE public.employees CASCADE;
TRUNCATE public.partners CASCADE;
TRUNCATE public.users CASCADE;

-- Insert sample users with valid UUIDs
INSERT INTO public.users (auth_id, email, username, role, avatar_url, status, theme_preference, language) VALUES
    ('550e8400-e29b-41d4-a716-446655440000', 'admin@storylab.com', 'admin', 'admin', 'https://api.dicebear.com/7.x/avatars/svg?seed=admin', 'active', 'system', 'ar-SA'),
    ('550e8400-e29b-41d4-a716-446655440001', 'partner1@storylab.com', 'partner1', 'partner', 'https://api.dicebear.com/7.x/avatars/svg?seed=partner1', 'active', 'light', 'ar-SA'),
    ('550e8400-e29b-41d4-a716-446655440002', 'partner2@storylab.com', 'partner2', 'partner', 'https://api.dicebear.com/7.x/avatars/svg?seed=partner2', 'active', 'dark', 'ar-SA'),
    ('550e8400-e29b-41d4-a716-446655440003', 'manager1@storylab.com', 'manager1', 'manager', 'https://api.dicebear.com/7.x/avatars/svg?seed=manager1', 'active', 'system', 'ar-SA'),
    ('550e8400-e29b-41d4-a716-446655440004', 'employee1@storylab.com', 'employee1', 'employee', 'https://api.dicebear.com/7.x/avatars/svg?seed=employee1', 'active', 'light', 'ar-SA'),
    ('550e8400-e29b-41d4-a716-446655440005', 'employee2@storylab.com', 'employee2', 'employee', 'https://api.dicebear.com/7.x/avatars/svg?seed=employee2', 'active', 'dark', 'ar-SA');

-- Insert sample partners
INSERT INTO public.partners (user_id, full_name, email, phone_number, profile_picture_url, specialization, company_name, business_type, tax_number, registration_number, address, city, country) VALUES
    (2, 'أحمد محمد', 'partner1@storylab.com', '+966501234567', 'https://api.dicebear.com/7.x/avatars/svg?seed=ahmed', 'Digital Marketing', 'Tech Solutions', 'Technology', 'TX123456789', 'RG987654321', 'شارع الملك فهد', 'الرياض', 'المملكة العربية السعودية'),
    (3, 'سارة عبدالله', 'partner2@storylab.com', '+966507654321', 'https://api.dicebear.com/7.x/avatars/svg?seed=sarah', 'Content Creation', 'Creative Hub', 'Media', 'TX987654321', 'RG123456789', 'شارع الأمير محمد بن سلمان', 'جدة', 'المملكة العربية السعودية');

-- Insert sample employees
INSERT INTO public.employees (user_id, full_name, email, phone_number, department, position, employee_id, hire_date, reports_to, office_location, work_schedule, employment_type) VALUES
    (4, 'خالد العمري', 'manager1@storylab.com', '+966512345678', 'Operations', 'Operations Manager', 'EMP001', '2023-01-15', NULL, 'المكتب الرئيسي - الرياض', '9:00 AM - 5:00 PM', 'full-time'),
    (5, 'نورة السعيد', 'employee1@storylab.com', '+966523456789', 'Marketing', 'Content Specialist', 'EMP002', '2023-03-01', 4, 'المكتب الرئيسي - الرياض', '9:00 AM - 5:00 PM', 'full-time'),
    (6, 'فهد الشمري', 'employee2@storylab.com', '+966534567890', 'Design', 'UI/UX Designer', 'EMP003', '2023-04-15', 4, 'فرع جدة', '10:00 AM - 6:00 PM', 'full-time');

-- Insert sample user stats
INSERT INTO public.user_stats (user_id, projects_count, completion_rate, team_members_count, total_tasks, completed_tasks) VALUES
    (1, 15, 95.5, 8, 120, 115),
    (2, 8, 88.0, 3, 45, 40),
    (3, 6, 92.0, 2, 30, 28),
    (4, 12, 85.5, 5, 90, 77),
    (5, 4, 78.0, 0, 25, 20),
    (6, 3, 82.5, 0, 20, 17);

-- Insert sample tasks
INSERT INTO public.tasks (title, description, status, priority, assigned_to, created_by, due_date) VALUES
    ('تطوير واجهة المستخدم', 'تصميم وتطوير واجهة المستخدم الجديدة للتطبيق', 'pending', 'high', 6, 1, NOW() + INTERVAL '7 days'),
    ('إعداد حملة تسويقية', 'تخطيط وتنفيذ حملة تسويقية للمنتج الجديد', 'pending', 'medium', 5, 4, NOW() + INTERVAL '14 days'),
    ('تحديث محتوى الموقع', 'تحديث المحتوى وترجمته للغة العربية', 'in_progress', 'medium', 5, 4, NOW() + INTERVAL '5 days'),
    ('مراجعة التصاميم', 'مراجعة وتحسين التصاميم الحالية', 'completed', 'low', 6, 4, NOW() - INTERVAL '2 days'),
    ('إعداد التقرير الشهري', 'تجهيز تقرير الأداء الشهري', 'pending', 'high', 4, 1, NOW() + INTERVAL '2 days');

-- Update sequences
SELECT setval('public.users_id_seq', (SELECT MAX(id) FROM public.users));
SELECT setval('public.partners_id_seq', (SELECT MAX(id) FROM public.partners));
SELECT setval('public.employees_id_seq', (SELECT MAX(id) FROM public.employees));
SELECT setval('public.user_stats_id_seq', (SELECT MAX(id) FROM public.user_stats));
SELECT setval('public.tasks_id_seq', (SELECT MAX(id) FROM public.tasks)); 